// Auto-generated by i18n-plugin. Do not edit.
export const locales = ["de","en","ar"] as const;
export const cookieName = 'LOCALE';
export const cookieMaxAge = 34560000;

let _storage: import('node:async_hooks').AsyncLocalStorage<{ locale: string }> | null | undefined = undefined;

export function getLocale(): string {
  if (_storage) { const s = _storage.getStore(); if (s?.locale) return s.locale; }
  if (typeof document !== 'undefined') { const l = document.documentElement.lang; if (l) return l; }
  return 'de';
}

export function getLocales() { return locales; }

export function setLocale(locale: string): void {
  if (typeof document !== 'undefined' && (locales as readonly string[]).includes(locale)) document.documentElement.lang = locale;
}

export function getTextDirection(locale: string): string {
  return ['ar', 'he', 'fa', 'ur'].includes(locale) ? 'rtl' : 'ltr';
}

export function deLocalizeUrl(url: URL | string): URL {
  return typeof url === 'string' ? new URL(url) : url;
}

export async function runWithLocale<T>(locale: string, fn: () => T | Promise<T>): Promise<T> {
  if (_storage === undefined) {
    try {
      const { AsyncLocalStorage } = await import(/* @vite-ignore */ 'node:async_hooks');
      _storage = new AsyncLocalStorage();
    } catch {
      _storage = null;
    }
  }
  if (_storage) return _storage.run({ locale }, fn) as Promise<T>;
  return fn() as Promise<T>;
}

const _li: Record<string, number> = {"de":0,"en":1,"ar":2};

function _t(tr: string[], p?: Record<string, string | number>): string {
  const text = tr[_li[getLocale()] ?? 0] ?? tr[0] ?? '';
  if (!p) return text;
  return text.replace(/\{(\w+)\}/g, (_, k) => String(p[k] ?? '{' + k + '}'));
}

export function hello_world(p?: Record<string, string | number>): string { return _t(["Hallo, {name}!","Hello, {name}!","مرحبا يا {name}!"], p); }
export function nav_home(p?: Record<string, string | number>): string { return _t(["Startseite","Home","الرئيسية"], p); }
export function nav_about(p?: Record<string, string | number>): string { return _t(["Über uns","About Us","من نحن"], p); }
export function nav_catalog(p?: Record<string, string | number>): string { return _t(["Katalog","Catalog","الكتالوج"], p); }
export function nav_blog(p?: Record<string, string | number>): string { return _t(["Blog","Blog","المدونة"], p); }
export function nav_communication(p?: Record<string, string | number>): string { return _t(["Kontakt","Contact","اتصل بنا"], p); }
export function hero(p?: Record<string, string | number>): string { return _t(["Verleihen Sie den Geschmäckern Ihre persönliche Note.","Put your signature on different tastes.","ضع توقيعك على الأذواق المختلفة"], p); }
export function footer_tagline(p?: Record<string, string | number>): string { return _t(["Kaffee- & Cocktail-Sirupe und Aromen","Coffee & Cocktail Syrups and Aromas","شراب وأرومات القهوة والكوكتيل"], p); }
export function footer_nav(p?: Record<string, string | number>): string { return _t(["Navigation","Navigation","التنقل"], p); }
export function footer_products(p?: Record<string, string | number>): string { return _t(["Produkte","Products","المنتجات"], p); }
export function footer_copyright(p?: Record<string, string | number>): string { return _t(["© 2026 Gusse Gıda EU. Alle Rechte vorbehalten.","© 2026 Gusse Gıda EU. All Rights Reserved.","© 2026 Gusse Gıda EU. جميع الحقوق محفوظة."], p); }
export function product_syrups(p?: Record<string, string | number>): string { return _t(["Sirupe","Syrups","شراب"], p); }
export function product_topping(p?: Record<string, string | number>): string { return _t(["Topping-Saucen","Topping Sauces","صلصة التوبينغ"], p); }
export function product_fruit_sauces(p?: Record<string, string | number>): string { return _t(["Fruchtsaucen","Fruit Sauces","صلصات الفاكهة"], p); }
export function product_deco_sauces(p?: Record<string, string | number>): string { return _t(["Dekorsaucen","Decoration Sauces","صلصات الزينة"], p); }
export function product_bar_sauces(p?: Record<string, string | number>): string { return _t(["Bar-Saucen","Bar Sauces","صلصات البار"], p); }
export function product_powder_drinks(p?: Record<string, string | number>): string { return _t(["Pulvergetränke","Powder Drinks","مشروبات بودرة"], p); }
export function product_ice_cream_paste(p?: Record<string, string | number>): string { return _t(["Eiskrem-Paste","Ice Cream Paste","معجون الآيس كريم"], p); }
export function product_herbal_teas(p?: Record<string, string | number>): string { return _t(["Kräutertees","Herbal Teas","شاي الأعشاب"], p); }
