// Auto-generated by i18n-plugin. Do not edit.
export const locales = ["de","en","ar","tr"] as const;
export const cookieName = 'LOCALE';
export const cookieMaxAge = 34560000;

let _storage: import('node:async_hooks').AsyncLocalStorage<{ locale: string }> | null | undefined = undefined;

export function getLocale(): string {
  if (_storage) { const s = _storage.getStore(); if (s?.locale) return s.locale; }
  if (typeof document !== 'undefined') { const l = document.documentElement.lang; if (l) return l; }
  return 'de';
}

export function getLocales() { return locales; }

export function setLocale(locale: string): void {
  if (typeof document !== 'undefined' && (locales as readonly string[]).includes(locale)) document.documentElement.lang = locale;
}

export function getTextDirection(locale: string): string {
  return ['ar', 'he', 'fa', 'ur'].includes(locale) ? 'rtl' : 'ltr';
}

export function deLocalizeUrl(url: URL | string): URL {
  return typeof url === 'string' ? new URL(url) : url;
}

export async function runWithLocale<T>(locale: string, fn: () => T | Promise<T>): Promise<T> {
  if (_storage === undefined) {
    try {
      const { AsyncLocalStorage } = await import(/* @vite-ignore */ 'node:async_hooks');
      _storage = new AsyncLocalStorage();
    } catch {
      _storage = null;
    }
  }
  if (_storage) return _storage.run({ locale }, fn) as Promise<T>;
  return fn() as Promise<T>;
}

const _li: Record<string, number> = {"de":0,"en":1,"ar":2,"tr":3};

function _t(tr: string[], p?: Record<string, string | number>): string {
  const text = tr[_li[getLocale()] ?? 0] ?? tr[0] ?? '';
  if (!p) return text;
  return text.replace(/\{(\w+)\}/g, (_, k) => String(p[k] ?? '{' + k + '}'));
}

export function hello_world(p?: Record<string, string | number>): string { return _t(["Hallo, {name}!","Hello, {name}!","مرحبا يا {name}!","Merhaba, {name}!"], p); }
export function nav_home(p?: Record<string, string | number>): string { return _t(["Startseite","Home","الرئيسية","Ana Sayfa"], p); }
export function nav_about(p?: Record<string, string | number>): string { return _t(["Über uns","About Us","من نحن","Hakkımızda"], p); }
export function nav_products(p?: Record<string, string | number>): string { return _t(["Produkte","Products","المنتجات","Ürünler"], p); }
export function nav_catalog(p?: Record<string, string | number>): string { return _t(["Katalog","Catalog","الكتالوج","Katalog"], p); }
export function nav_blog(p?: Record<string, string | number>): string { return _t(["Blog","Blog","المدونة","Blog"], p); }
export function nav_communication(p?: Record<string, string | number>): string { return _t(["Kontakt","Contact","اتصل بنا","İletişim"], p); }
export function hero(p?: Record<string, string | number>): string { return _t(["Verleihen Sie den Geschmäckern Ihre persönliche Note.","Put your signature on different tastes.","ضع توقيعك على الأذواق المختلفة","Tatlarınıza kendi imzanızı atın."], p); }
export function hero_cta_products(p?: Record<string, string | number>): string { return _t(["Produkte entdecken","Discover Products","اكتشف المنتجات","Ürünleri Keşfedin"], p); }
export function hero_cta_catalog(p?: Record<string, string | number>): string { return _t(["Katalog herunterladen","Download Catalog","تحميل الكتالوج","Kataloğu İndir"], p); }
export function footer_tagline(p?: Record<string, string | number>): string { return _t(["Kaffee- & Cocktail-Sirupe und Aromen","Coffee & Cocktail Syrups and Aromas","شراب وأرومات القهوة والكوكتيل","Kahve ve Kokteyl Şurupları ve Aromaları"], p); }
export function footer_nav(p?: Record<string, string | number>): string { return _t(["Navigation","Navigation","التنقل","Navigasyon"], p); }
export function footer_products(p?: Record<string, string | number>): string { return _t(["Produkte","Products","المنتجات","Ürünler"], p); }
export function footer_copyright(p?: Record<string, string | number>): string { return _t(["© 2026 Gusse Gıda EU. Alle Rechte vorbehalten.","© 2026 Gusse Gıda EU. All Rights Reserved.","© 2026 Gusse Gıda EU. جميع الحقوق محفوظة.","© 2026 Gusse Gıda EU. Tüm hakları saklıdır."], p); }
export function product_syrups(p?: Record<string, string | number>): string { return _t(["Sirupe","Syrups","شراب","Şuruplar"], p); }
export function product_topping(p?: Record<string, string | number>): string { return _t(["Topping-Saucen","Topping Sauces","صلصة التوبينغ","Topping Sosları"], p); }
export function product_fruit_sauces(p?: Record<string, string | number>): string { return _t(["Fruchtsaucen","Fruit Sauces","صلصات الفاكهة","Meyve Sosları"], p); }
export function product_deco_sauces(p?: Record<string, string | number>): string { return _t(["Dekorsaucen","Decoration Sauces","صلصات الزينة","Dekor Sosları"], p); }
export function product_bar_sauces(p?: Record<string, string | number>): string { return _t(["Bar-Saucen","Bar Sauces","صلصات البار","Bar Sosları"], p); }
export function product_powder_drinks(p?: Record<string, string | number>): string { return _t(["Pulvergetränke","Powder Drinks","مشروبات بودرة","Toz İçecekler"], p); }
export function product_ice_cream_paste(p?: Record<string, string | number>): string { return _t(["Eiskrem-Paste","Ice Cream Paste","معجون الآيس كريم","Dondurma Patesi"], p); }
export function product_herbal_teas(p?: Record<string, string | number>): string { return _t(["Kräutertees","Herbal Teas","شاي الأعشاب","Bitki Çayları"], p); }
export function product_frozen(p?: Record<string, string | number>): string { return _t(["Tiefkühl","Frozen Products","منتجات مجمدة","Dondurulmuş Ürünler"], p); }
export function feature_syrups_title(p?: Record<string, string | number>): string { return _t(["Erstklassige Sirupe","Premium Syrups","شرابات متميزة","Birinci Sınıf Şuruplar"], p); }
export function feature_syrups_text(p?: Record<string, string | number>): string { return _t(["Über 100 Sirupsorten für Kaffee, Cocktails und Desserts - entwickelt von erfahrenen Lebensmittelingenieuren in enger Zusammenarbeit mit Barpersonal aus der ganzen Türkei.","Over 100 syrup varieties for coffee, cocktails and desserts - developed by experienced food engineers in close collaboration with bar professionals across Turkey.","أكثر من 100 نوع من الشرابات للقهوة والكوكتيل والحلويات - طوّرها مهندسو الأغذية ذوو الخبرة.","Kahve, kokteyl ve tatlılar için 100'den fazla şurup çeşidi - deneyimli gıda mühendisleri tarafından geliştirildi."], p); }
export function feature_lemonade_title(p?: Record<string, string | number>): string { return _t(["Tiefkühl-Limonaden","Frozen Lemonades","عصائر مجمدة","Dondurulmuş Limonatalar"], p); }
export function feature_lemonade_text(p?: Record<string, string | number>): string { return _t(["Fruchtige Tiefkühl-Limonaden für Cafés und Bars - einfach in der Zubereitung, unvergleichlich im Geschmack. Direkt aus unserer Produktion in Çerkezköy.","Fruity frozen lemonades for cafés and bars - easy to prepare, unmatched in taste. Directly from our production facility in Çerkezköy.","عصائر فواكه مجمدة للمقاهي والبارات - سهلة التحضير، لا مثيل لها في الطعم.","Kafeler ve barlar için meyveli dondurulmuş limonatalar - hazırlaması kolay, tadı benzersiz."], p); }
export function feature_coffee_title(p?: Record<string, string | number>): string { return _t(["Haseki Sultan & La Ferme","Haseki Sultan & La Ferme","هاسكي سلطان ولا فيرم","Haseki Sultan & La Ferme"], p); }
export function feature_coffee_text(p?: Record<string, string | number>): string { return _t(["Unsere Eigenmarken für Kaffee-Aromen und Sirupe - entwickelt für den professionellen Einsatz in Cafés und Restaurants weltweit.","Our own brands for coffee aromas and syrups - developed for professional use in cafés and restaurants worldwide.","علاماتنا التجارية الخاصة لنكهات القهوة والشرابات - مطوّرة للاستخدام المهني.","Kahve aromaları ve şurupları için kendi markalarımız - dünya genelinde profesyonel kullanım için geliştirildi."], p); }
export function products_count(p?: Record<string, string | number>): string { return _t(["{count} Produkte","{count} Products","{count} منتج","{count} ürün"], p); }
